name: Build wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#  schedule:
#    - cron: '0 0 * * sun,wed'

jobs:
  build_wheels:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.1
        env:
          CIBW_ARCHS_LINUX: x86_64
          #CIBW_ARCHS_MACOS: ""
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_BUILD: cp310-* cp311-* cp312-* cp313-*
          CIBW_SKIP: pp* *i686 *-musllinux_* *-win32
          #CIBW_TEST_COMMAND: pytest -rfxEXs --durations=20 --disable-warnings --showlocals --pyargs datrie
          #CIBW_TEST_REQUIRES: pytest testfixtures mock
          #CIBW_TEST_SKIP: "win*"
          CIBW_BUILD_VERBOSITY: 3

      - name: Upload wheels as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  test:
    name: Test ${{ matrix.os }} Py${{ matrix.python }}
    needs: build_wheels
    strategy:
      fail-fast: false
      matrix:
        include:
          - {python: '3.10', os: ubuntu-22.04}
          - {python: '3.11', os: ubuntu-22.04}
          - {python: '3.12', os: ubuntu-22.04}

          - {python: '3.10', os: windows-2022}
          - {python: '3.11', os: windows-2022}
          - {python: '3.12', os: windows-2022}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Downloads build artifacts
        uses: actions/download-artifact@v4
        id: download
        with:
          name: wheels-${{ matrix.os }}
          path: artifacts/wheels-${{ matrix.os }}.zip

      - name: Unzip build artifacts
        run: unzip ${{steps.download.outputs.download-path}}
      
      - name: Install wheel in Linux
        if:  runner.os == 'Linux'
        run: pip install artifacts/wheels-${{ matrix.os }}/datrie-0.8.2-cp${{ matrix.python }}-cp${{ matrix.python }}-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

      - name: Install wheel in Windows
        if:  runner.os == 'Windows'
        run: pip install artifacts/wheels-${{ matrix.os }}/datrie-0.8.2-cp${{ matrix.python }}-cp${{ matrix.python }}-win_amd64.whl

  
      # If the wheel was incorrectly built, then this will fail.
      - name: Test wheel
        run: python -c 'import datrie'